version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-container
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - data:/data

  python-app:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: python-app-container
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: "bolt://neo4j:7687"
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password

volumes:
  neo4j-data:
    driver: local
